#!/usr/bin/env php
<?php

require_once 'vendor/autoload.php';

use Symfony\Component\Console\Application;

$application = new Application('Synap/EBICS', 'dev');
$application->add(new Synap\EBICS\Command\HEVCommand);
$application->add(new Synap\EBICS\Command\INICommand);
$application->run();
